POST http://localhost:8080/freelancer
Content-Type: application/json

# info
# mailReceptionState 구성 {
#    RECEPTION("수신")
#    NOT_RECEPTION("미수신")
#}
# workPossibleState 구성 {
#    POSSIBLE("가능"),
#    IMPOSSIBLE("불가능")
# }
#

#req
{
  "memberName" : "memberName",
  "memberId" : "memberID",
  "memberPassword" : "password",
  "memberPasswordCheck" : "password",
  "memberEmail" : "membmer@email.com",
  "mailReceptionState" : "NOT_RECEPTION",
  "memberPhone" : "memberPhone",
  "workPossibleState" : "POSSIBLE",
  "workStartPossibleDate" : "2022-10-10",
  "thumbnail" : null
}
