PUT http://localhost:8080/freelancer-profile/etc
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cmlSUlJSUiIsImlhdCI6MTY1NTc5NTg5NiwiZXhwIjoxNjU1Nzk2MDE2fQ.czR41h4KQ2qZs1VO6Rd2LXlBbM9FQBSJQSx8SebW4BA

#info
# EtcDetailRole 구성 {
#    PM("PM"),
#    PL("PL"),
#    SYSTEM_ANALYSIS_AND_PLAN("시스템분석/설계"),
#    DA("DA"),
#    DBA("DBA"),
#    TA("TA"),
#    AA("AA"),
#    NA("NA"),
#    PMO("PMO"),
#    SE("SE"),
#    QA("QA"),
#    QC("QC")
#}
#

#req
{
  "etcDetailRoles": [
    "PM", "PL", "DBA"
  ],
  "positionEtcRole": "etcRole"
}

