PUT http://localhost:8080/freelancer-profile/planner
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cmlSUlJSUiIsImlhdCI6MTY1NTc5NTg5NiwiZXhwIjoxNjU1Nzk2MDE2fQ.czR41h4KQ2qZs1VO6Rd2LXlBbM9FQBSJQSx8SebW4BA


#info
# PlannerDetailField 구성 {
#    PM("PM"),
#    PL("PL"),
#    PMO("PMO(사업관리)"),
#    SYSTEM_ANALYSIS_AND_PLAN("시스템분석/설계"),
#    WEB_PLAN("웹기획"),
#    APP_PLAN("앱기획"),
#    CONSULTING("컨설팅"),
#    OFFER("제안"),
#    SHOPPING_MALL("쇼핑몰"),
#    TRAVEL_AGENCY("여행사"),
#    FINANCE("금융"),
#    STOCK("증권"),
#    CARD("카드"),
#    INSURANCE("보험"),
#    UNIVERSITY("대학"),
#    HOSPITAL("병원"),
#    PUBLIC_OFFICE("공공기관"),
#    DISTRIBUTION("물류"),
#    ACCOUNTING("회계"),
#    PRODUCTION("제조"),
#    CONSTRUCTION("건설"),
#    CRYPTOCURRENCY("암호화폐")
# }
#

#req
{
  "plannerDetailFields": [
    "SHOPPING_MALL", "PM"
  ],
  "etcField": "etcField"
}