PUT http://localhost:8080/freelancer-profile/1/publisher
Content-Type: application/json

#info
# PublishingDetailSkill 구성 {
#    HTML5("HTML5"),
#    CSS("CSS"),
#    ACTIONSCRIPT("ActionScript"),
#    JQUERY("jQuery"),
#    REACT_JS("React.js"),
#    VUE_JS("Vue.js"),
#    JAVASCRIPT("JavaScript"),
#    WORDPRESS("WordPress"),
#    BOOTSTRAP("BootStrap"),
#    PHOTOSHOP("Photoshop"),
#    FLASH("Flash"),
#    WEB_ACCESSIBILITY("웹접근성"),
#    WEB_STANDARD("웹표준"),
#    GIT("Git")
#}
#


#req
{
  "publishingDetailSkills": [
    "HTML5", "CSS", "JQUERY"
  ],
  "etcSkill": "etcSkill"
}

