PUT http://localhost:8080/freelancer-profile/1/designer
Content-Type: application/json

#info
# DesignDetailRole 구성 {
#    WEB_DESIGN("웹디자인"),
#    APP_DESIGN("앱디자인"),
#    PUBLISH_AND_EDIT_DESIGN("출판/편집 디자인"),
#    GAME_DESIGN("게임 디자인"),
#    FREEBIE_DESIGN("판촉물 디자인"),
#    THREED_DESIGN("3D 디자인"),
#    GRAPHIC_DESIGN("그래픽 디자인"),
#    PACKAGE_DESIGN("패키지 디자인"),
#    ART_DIRECTION("아트 디렉션"),
#    ANIMATION("애니메이션"),
#    LOGO_BRANDING("로고 브랜딩")
#}
#
# DesignDetailSkill 구성 {
#    AFERE_EFFECT("Afere Effect"),
#    ILLUSTRATOR("Illustrator"),
#    INDESIGN("InDesign"),
#    PHOTOSHOP("Photoshop"),
#    SKETCH("Sketch"),
#    ZEPLIN("Zeplin"),
#    ADOBE_XD("Adobe XD"),
#    THREE_D_MAX_AND_MAYA("3D Max/Maya"),
#    CLIP_STUDIO("CLIP STUDIO"),
#    MEDIBANG("MediBang"),
#    FLASH("Flash")
#}
#


#req
{
  "designDetailRoles": [
    "WEB_DESIGN", "GRAPHIC_DESIGN", "GAME_DESIGN"
  ],
  "etcRole": "etcRole",
  "designDetailSkills": [
    "AFERE_EFFECT", "SKETCH", "INDESIGN"
  ],
  "etcSkill": "etcSkill"
}

