GET http://localhost:8080/freelancer-profile/1/designer
Content-Type: application/json

#res
#{
#  "designDetailRoles": [
#    "WEB_DESIGN",
#    "GRAPHIC_DESIGN",
#    "GAME_DESIGN"
#  ],
#  "etcRole": "etcRole",
#  "designDetailSkills": [
#    "AFERE_EFFECT",
#    "SKETCH",
#    "INDESIGN"
#  ],
#  "etcSkill": "etcSkill"
#}
#
#Response code: 201; Time: 323ms; Content length: 167 bytes