GET http://localhost:8080/profile-enums
Content-Type: application/json

#res
#
#{
#  "schoolLevelNames": [
#    "고등학교",
#    "대학교(2,3년)",
#    "대학교(4년)",
#    "대학원(석사)",
#    "대학원(박사)"
#  ],
#  "academicStateNames": [
#    "재학",
#    "휴학",
#    "중퇴",
#    "졸업",
#    "수료/이수"
#  ],
#  "companyPositionNames": [
#    "회장",
#    "부회장",
#    "사장",
#    "부사장",
#    "전무",
#    "상무",
#    "이사",
#    "부장",
#    "차장",
#    "과장",
#    "실장",
#    "팀장",
#    "대리",
#    "계장",
#    "주임",
#    "사원",
#    "연구소장",
#    "수석 연구원",
#    "책임 연구원",
#    "선임 연구원",
#    "주임 연구원",
#    "연구원",
#    "임시직",
#    "기타",
#    "매니저"
#  ],
#  "languageAbilityNames": [
#    "일상회화 가능",
#    "비즈니스 회화가능",
#    "원어민 수준"
#  ]
#}
#
#Response code: 200; Time: 101ms; Content length: 351 bytes